### ISSUE TITLE
Repeat "put prototype back"

### ISSUE THREAD

**Issue by MrMcX** [ubilab-escape/operator#63]
Every 5 seconds

**Comment by jrebmann** [comment]
Saurav Shanu

**Comment by jrebmann** [comment]
Sended message to Saurav:

Hi Saurav,
17:09 Uhr
is it possible to extend the text-to-Speech module with an parameter how often a given sentence is repeated until it's stopped?
17:13 Uhr
there is a new requirement to continous repeat the sentence "put the prototype back" until the weight of the scale is balanced again.
It would save us much time just to trigger and stop that continous repeation with a simple MQTT command.
It would be very nice if you can implement that for us.
17:13 Uhr
best regards Jannik

**Comment by jrebmann** [comment]
Ist es nicht so, dass wir sowieso einen service für den Alarm am laufen haben? Wäre es nicht viel einfacher diese Textausgabe-Wiederholung in unserem Service zu implementieren? Wir müssten ja sowieso ein Ausgabe-STOP senden wenn die Waage wieder ausbalanciert ist.

**Comment by MrMcX** [comment]
Ja, ich kann es auch da mit dazu nehmen

**Comment by jrebmann** [comment]
Saurav Shanu  17:23 Uhr
Hi Jannik
17:24 Uhr
How about just sending the message repeatedly with a delay of 1 second.
Jannik Rebmann  17:27 Uhr
:lächeln: ... yes this would be our fallback implementation. But in this case we need to implement an service for all use cases were we need an continous repeation of a sentence.
So we like to ask you how complex it would be to implement this as a default function of your module.
Neue Nachrichten
Saurav Shanu  17:30 Uhr
Actually, I have an exam next Monday and I haven't prepared much for it till now. I was trying to keep this week free for the preparation. That's why I am little hesitant to do that.
Jannik Rebmann  17:32 Uhr
okey ... I'm understanding. I will talk to Simon, maybe there is an easy way for us to implement this on our side.
